call ionic g c components/component1
call ionic g c components/component2
call ionic g c components/component3
call ionic g c components/component4
call ionic g c components/component5
call ionic g c components/component6
call ionic g c components/component7
call ionic g c components/component8
call ionic g c components/component9
call ionic g c components/component10
call ionic g c components/component11
call ionic g c components/component12
call ionic g c components/component13
call ionic g c components/component14
call ionic g c components/component15
call ionic g c components/component16
call ionic g c components/component17
call ionic g c components/component18
call ionic g c components/component19
call ionic g c components/component20
call ionic g c components/component21
call ionic g c components/component22
call ionic g c components/component23
call ionic g c components/component24
call ionic g c components/component25
call ionic g c components/component26
call ionic g c components/component27
call ionic g c components/component28
call ionic g c components/component29
call ionic g c components/component30